### ISSUE TITLE
Gremlin is not working SIGSEGV

### ISSUE THREAD

**Issue by janisz** [octopus-foundation/octopus#2]
I tried to run gremlin for my codebase https://github.com/stackrox/stackrox but it looks like it's tightly coupled with octopus and cannot be used outside of the framework as it ignores `-root` flag.
```go
Found root for all protobufs: github.com/stackrox/stackrox, total proto files: 853
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4b92f9]

goroutine 1 [running]:
octopus/build-tools/gremlin/internal.addPublicImports(...)
	octopus/build-tools/gremlin/internal/imports.go:68
octopus/build-tools/gremlin/internal.ResolveImportsAndReferences({0xc00025a000?, 0x355, 0x500?})
	octopus/build-tools/gremlin/internal/imports.go:48 +0x6b9
main.main()
	octopus/build-tools/gremlin/gremlin.go:70 +0x196
```

**Comment by batsuev** [comment]
fixed in https://github.com/norma-core/norma-core/tree/main/shared/gremlin_go
